#!/usr/bin/perl -w

use strict;

sub help() {
    print STDERR <<'HELP';
killnode - Quickly kill node processes

Args:
  help - see this message

https://github.com/jonbri/killnode

HELP
}

sub runCommand($) {
    my ($command) = @_;
    open CMD, "$command |" || die "Unable to run $command: $!";
    my @output = <CMD>;
    close CMD;
    return @output;
}

# give user a chance to back out before an operation
sub confirm($) {
    my ($message)=@_;
    print $message;
    print "\npress any key to continue... (ctrl-c to cancel)\n";
    my $ok=<>;
}

MAIN: {
    my $firstArg=shift @ARGV;
    if ($firstArg) {
        if ($firstArg eq "help" || $firstArg =~ /-(-)?h(elp)?/) {
            help();
        }
    }

    my @pidLineToKill = runCommand("ps aux | grep 'node ' | grep -v 'grep'");
    foreach (@pidLineToKill) {
        chomp;

        print "kill?\n-> ";
        confirm "$_\n";

        print "ok, invoke kill...\n";
        runCommand("sudo ls");
    }
}
